/**
 * @name PerfeAnnotation
 * @namespace PerfeAnnotation::types::Statictypes
 * @license MIT
 * @copyright 2023 - perfect-evolution
 * @author Mike Karypidis
 * @link https://github.com
 * @file Statictypes.js
 * @description This module exports different objects that hold string values representing the different types of the project, most used for enum cases.
 * 
 * ==================================
 * 
 * This module exports different objects that hold string values representing the different types of the project, most used for enum cases.
 * 
 * ==================================
 * 
 */

module.exports.LineType = {
  "DEFAULT_EXPORT_CLASS": "DEFAULT_EXPORT_CLASS",
  "NAMED_EXPORT_CLASS": "NAMED_EXPORT_CLASS",
  "DEFAULT_EXPORT_NAMED_FUNCTION": "DEFAULT_EXPORT_NAMED_FUNCTION",
  "DEFAULT_EXPORT_NAMED_ASYNC_FUNCTION": "DEFAULT_EXPORT_NAMED_ASYNC_FUNCTION",
  "NAMED_EXPORT_FUNCTION": "NAMED_EXPORT_FUNCTION",
  "NAMED_EXPORT_ASYNC_FUNCTION": "NAMED_EXPORT_ASYNC_FUNCTION",

  "CLASS_PROPERTY_WITHOUT_VALUE": "CLASS_PROPERTY_WITHOUT_VALUE",
  "CLASS_PROPERTY_WITH_VALUE": "CLASS_PROPERTY_WITH_VALUE",
  "CLASS_ASYNC_METHOD": "CLASS_ASYNC_METHOD",
  "CLASS_METHOD": "CLASS_METHOD",

  "CLASS_STATIC_PROPERTY_WITHOUT_VALUE": "CLASS_STATIC_PROPERTY_WITHOUT_VALUE",
  "CLASS_STATIC_PROPERTY_WITH_VALUE": "CLASS_STATIC_PROPERTY_WITH_VALUE",
  "CLASS_STATIC_METHOD": "CLASS_STATIC_METHOD",
  "CLASS_STATIC_ASYNC_METHOD": "CLASS_STATIC_ASYNC_METHOD",
  "NONE": "NONE"
}

module.exports.AnnotationType = {
  "DEFAULT_CLASS": "DEFAULT_CLASS",
  "CLASS": "CLASS",
  "DEFAULT_FUNCTION": "DEFAULT_FUNCTION",
  "DEFAULT_ASYNC_FUNCTION": "DEFAULT_ASYNC_FUNCTION",
  "FUNCTION": "FUNCTION",
  "ASYNC_FUNCTION": "ASYNC_FUNCTION",

  "CLASS_PROPERTY_UNINITIALIZED": "CLASS_PROPERTY_UNINITIALIZED",
  "CLASS_PROPERTY": "CLASS_PROPERTY",
  "CLASS_ASYNC_METHOD": "CLASS_ASYNC_METHOD",
  "CLASS_METHOD": "CLASS_METHOD",

  "CLASS_STATIC_PROPERTY_UNINITIALIZED": "CLASS_STATIC_PROPERTY_UNINITIALIZED",
  "CLASS_STATIC_PROPERTY": "CLASS_STATIC_PROPERTY",
  "CLASS_STATIC_ASYNC_METHOD": "CLASS_STATIC_ASYNC_METHOD",
  "CLASS_STATIC_METHOD": "CLASS_STATIC_METHOD"
}